name: CI/CD

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Test PirateScroll
      working-directory: ./addons/PirateScroll
      run: |
        npm ci
        npm run test --if-present
        
    - name: Test EpisoNext
      working-directory: ./addons/episonext
      run: |
        npm ci
        npm run test --if-present
        
    - name: Test Stremio-Customizer
      working-directory: ./addons/stremio-customizer
      run: |
        npm ci
        npm run test --if-present

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Deploy PirateScroll
      working-directory: ./addons/PirateScroll
      run: |
        npm ci
        npm run build --if-present
      env:
        CI: true 